import { chromium } from 'playwright-core';
const [, , url, out, theme = 'light'] = process.argv;
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const page = await browser.newPage({ viewport: { width: 1440, height: 1100 }, colorScheme: theme });
await page.goto(url, { waitUntil: 'load' }).catch(() => {});
await page.waitForTimeout(3000);
await page.goto(url, { waitUntil: 'load' });
await page.waitForTimeout(2500);
await page.screenshot({ path: out, fullPage: true });
await browser.close();
console.log('ok', out);
